### ISSUE TITLE
Unclosed client session

### ISSUE THREAD

**Issue by MeinOfenBrennt** [killer0071234/python-zamg#212]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020CFE6C6550>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000020CFE73C520>, 352568.39)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000020CFF040C10>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000020CFF022220>
transport: <_ProactorSocketTransport fd=932 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\Arnold\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\Arnold\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\Arnold\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000020CFE5AC1F0>
Traceback (most recent call last):
  File "C:\Users\Arnold\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Users\Arnold\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Users\Arnold\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "C:\Users\Arnold\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "C:\Users\Arnold\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "C:\Users\Arnold\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "C:\Users\Arnold\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Users\Arnold\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Users\Arnold\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

kommm da leider nicht weiter? (Beispielcode)
Aber ein super Tool ist die Klasse :-)

Danke Lg

**Comment by MeinOfenBrennt** [comment]
python lib problem
